services:
  club.payment.quickpay.listener:
    class: Club\Payment\QuickpayBundle\Listener\Quickpay
    arguments: [@service_container]
    tags:
      - { name: kernel.event_listener, event: paymentmethod.get, method: onPaymentMethodGet }
