<?php

namespace Club\Payment\QuickpayBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DrawRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrawRepository extends EntityRepository
{
}
